# Generated by Django 2.1.7 on 2019-10-07 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_animal', models.CharField(help_text='*', max_length=64, verbose_name='Nombre Animal')),
                ('nombre_latin', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre Latin')),
                ('descripcion', models.CharField(blank=True, max_length=64, null=True, verbose_name='Descripcion')),
                ('region', models.CharField(help_text='*', max_length=64, verbose_name='Region')),
                ('alimentacion', models.CharField(blank=True, max_length=64, null=True, verbose_name='Alimentacion')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animal',
            },
        ),
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=128, verbose_name='Cantidad')),
                ('fecha_avistamiento', models.DateField(verbose_name='Fecha de avistamiento')),
                ('comentario', models.CharField(help_text='*', max_length=100, verbose_name='Comentario')),
                ('animal_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animal',
            },
        ),
    ]
