# Generated by Django 2.2.4 on 2019-10-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_finca', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre Finca')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre Genero')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especie', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre Especie')),
                ('clase', models.CharField(blank=True, max_length=64, null=True)),
                ('dieta', models.CharField(blank=True, max_length=64, null=True)),
                ('genero_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genero')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_camara', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre Camara')),
                ('ubicacion_latitud', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ubicacion Latitud')),
                ('ubicacion_longitud', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ubicacion Longitud')),
                ('finca_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Finca')),
            ],
            options={
                'verbose_name': 'Camara',
                'verbose_name_plural': 'Camaras',
            },
        ),
        migrations.CreateModel(
            name='Avistamientom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_de_individuos', models.IntegerField(blank=True, null=True, verbose_name='Numero de Individuos')),
                ('temperatura', models.IntegerField(blank=True, null=True, verbose_name='Temperatura')),
                ('fecha_avistamiento', models.DateField(verbose_name='Fecha de avistamiento')),
                ('hora_avistamientos', models.TimeField(verbose_name='Hora de avistamientos')),
                ('fase_lunar', models.CharField(blank=True, max_length=64, null=True, verbose_name='Fase Lunar')),
                ('memoria', models.CharField(blank=True, max_length=64, null=True, verbose_name='Memoria')),
                ('video', models.CharField(blank=True, max_length=64, null=True, verbose_name='Video')),
                ('camara_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Camara')),
                ('especie_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Especie')),
                ('finca_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Finca')),
            ],
            options={
                'verbose_name': 'Avistamiento',
                'verbose_name_plural': 'Avistamientos',
            },
        ),
    ]
